POSTGRES_USER="postgres"
POSTGRES_PW="xxx"
POSTGRES_HOST="outside"
POSTGRES_DB="infinite-api"
POSTGRES_PORT=5436

SLACK_WEBHOOK_TEST="https://hooks.slack.com/services/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"
SLACK_WEBHOOK_CONTACT="https://hooks.slack.com/services/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"
SLACK_WEBHOOK_EVENT_SUBMISSION="https://hooks.slack.com/services/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"
SLACK_WEBHOOK_VENUE_SUBMISSION="https://hooks.slack.com/services/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"

BITLY_TOKEN=401cbf1121b4859d3a0c8f09b623193eb0233fac
APP_URL=https://staging.infinite.industries:7779

PRIVATE_KEY_PATH=../../api-server/keys


POSTGRES_PW
POSTGRES_HOST
POSTGRES_DB
POSTGRES_PORT

SLACK_WEBHOOK_TEST
SLACK_WEBHOOK_CONTACT
SLACK_WEBHOOK_EVENT_SUBMISSION
SLACK_WEBHOOK_VENUE_SUBMISSION

BITLY_TOKEN
APP_URL

PRIVATE_KEY_PATH

POSTGRES_USER=$POSTGRES_USER docker-compose up